language: node_js
node_js:
  - '0.12'
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - node_modules
addons:
  code_climate:
    repo_token: 2e228780043451e7016751380ed6259755cfd8b1e1cf9dffaee3d2e1d39677b1
